apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 8080;

      location /api/v1/movies {
        proxy_pass http://fastapi-movie-service:{{ .Values.fastapi.movie.service.port }}/api/v1/movies;
      }

      location /api/v1/casts {
        proxy_pass http://fastapi-cast-service:{{ .Values.fastapi.cast.service.port }}/api/v1/casts;
      }
    }