apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fastapi-cast-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastapi-cast-deployment
  minReplicas: {{ .Values.fastapi_cast.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.fastapi_cast.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.fastapi_cast.autoscaling.targetCPUUtilizationPercentage }}
