apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress
  namespace: staging
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - hosts:
    - devops.dev-euphony.fr
    secretName: rancher-secret
  rules:
  - host: devops.dev-euphony.fr
    http:
      paths:
      - pathType: Prefix
        path: "/api/v1/movies"
        backend:
          service:
            name: fastapi-movie-service
            port:
              number: 80
